### ISSUE TITLE
To use `*` selector in a container is dangerous

### ISSUE THREAD

**Issue by Dafrok** [picturepan2/devices.css#6]
The code below makes all elements in the device container to be block level, that's not a good idea I suppose.

```scss
.device,
.device * {
  &,
  &::before,
  &::after {
    box-sizing: border-box;
    display: block;
  }
}
```

> https://github.com/picturepan2/devices.css/blob/f8a06c18ea14654ba379b409eaa08aed70d87375/src/_reset.scss#L3

**Comment by do-adams** [comment]
I agree, this seems like bad practice. This CSS makes it impossible to properly render nested HTML content within the `.device-content` block of the `.device`.

I managed to fix this by overriding the base device styles with this:
```css
.device,
.device::before,
.device::after,
.device > *,
.devie > * > *,
.device > *::before,
.device > *::after,
.device > * > *::before,
.device > * > *::after {
  box-sizing: border-box;
  display: block;
}
```

It works well so long as the device structure follows the pattern (which all of the devices as of v0.1.16 do):
```html
<div class="device device-iphone-x">
  <div class="device-frame">
    <img class="device-content" src="...">
  </div>
  <div class="device-stripe"></div>
  <div class="device-header"></div>
  <div class="device-sensors"></div>
  <div class="device-btns"></div>
  <div class="device-power"></div>
</div>
```

I hope this helps anyone else who's running into the same issue!
